from datetime import datetime, timezone
from .db import get_db

async def audit(tenant_id, actor, action, entity, entity_id=None, details=None):
    """Write the audit row and create one idempotent admin notification.

    Notifications are created at write time instead of being generated by the
    notification GET endpoint. This keeps dashboard reads read-only and fast.
    """
    db = get_db()
    now = datetime.now(timezone.utc)
    result = await db.audit_logs.insert_one({
        "tenant_id": tenant_id,
        "actor_id": str(actor["_id"]),
        "actor_phone": actor.get("phone"),
        "action": action,
        "entity": entity,
        "entity_id": entity_id,
        "details": details or {},
        "created_at": now,
    })
    if tenant_id:
        key=f"audit:{result.inserted_id}"
        notif_type="loan_request" if action=="LOAN_REQUESTED" else "activity"
        notif_title="New loan request" if action=="LOAN_REQUESTED" else str(action or "Activity").replace("_", " ").title()
        amount=(details or {}).get("amount") if isinstance(details,dict) else None
        notif_body=(f"A member has requested ₹{float(amount):,.2f}." if action=="LOAN_REQUESTED" and amount is not None else "New group activity recorded.")
        try:
            await db.notifications.update_one(
                {"tenant_id": tenant_id, "source_key": key},
                {"$setOnInsert": {
                    "tenant_id": tenant_id, "recipient_role": "admin", "type": notif_type,
                    "title": notif_title, "body": notif_body, "read": False,
                    "created_at": now, "source_key": key,
                }}, upsert=True
            )
        except Exception:
            # Audit logging must never fail the business transaction because a
            # notification record is malformed or unavailable.
            pass
